try:
    1/0
except Exception as e:
    print(e)    # 输出异常信息
